name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@master
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
        
      - name: Install dependencies and build
        run: |
          sudo gem install jekyll bundler
          bundle install
          bundle exec jekyll build
          echo "ğŸ This job's status is ${{ job.status }}."
          
      - name: Deploy
        uses: ChrisFiola/github-action-build@master
        with:
          branch: master
          folder: docs
