name: GitHub Actions Test To Build Site in /docs
on: [push]
jobs:
  Build-With-Jekyll:
    runs-on: ubuntu-latest
    steps:
      - run: sudo gem install jekyll bundler
      - name: Check. out repository code
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: bundle install
      - run: bundle exec jekyll build
      - run: echo "ğŸ This job's status is ${{ job.status }}."
