name: GitHub Actions Test To Build Site in /docs
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: sudo gem install jekyll bundler
      - run: sudo bundle install
      - run: bundle exec jekyll build
      - run: echo "ğŸ This job's status is ${{ job.status }}."
